name: scanner_document
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  percent_indicator: ^4.2.3
  camera: ^0.10.5
  path_provider: ^2.0.15
  path: ^1.8.2
  modal_bottom_sheet: ^2.1.2
  flutter_launcher_icons: ^0.13.1
  image_picker: ^0.8.7+5
  cross_file: ^0.3.3+4
  photo_manager: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
